# This is a basic workflow to help you get started with Actions

name: Compilar ejemplo Specflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
    
      SPECFLOW_PROJECT: SpecFlow.Ejemplo
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: wakoagui/mono:latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # - name: Instalar certificados
     #   run: |
     #           sudo apt install gnupg ca-certificates
     #           sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF 
     #           echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo  tee /etc/apt/sources.list.d/mono-official-stable.list
     #           sudo apt update 
     #           sudo apt install -y mono-devel
      
      - name: Checkout project
        uses: actions/checkout@v2
  
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      
      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
      
      - name:  Instalar generador de documentacion
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
      
      - name: Generate LivingDoc documentation
        run: |
          export PATH="$PATH:/github/home/.dotnet/tools"
          livingdoc test-assembly ./$SPECFLOW_PROJECT/bin/Debug/netcoreapp3.1/$SPECFLOW_PROJECT.dll -t ./$SPECFLOW_PROJECT/bin/Debug/netcoreapp3.1/TestExecution.json --output ./docs/index.html
          
      - name: Instalar Rsync
        run: sudo apt-get install -y rsync 
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs # The folder the action should deploy.
        
